### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Lukas-Kadura** [Jerem584/PacketTracerRecovery#1]
good day, it keeps telling me the error Failed to find PacketTracer (Run this tool on the main menu of packet tracer) and I don't know what I'm doing wrong. I have Cisco Packet Treace 8.2.1 installed

**Comment by Jerem584** [comment]
Hi

Should be fixed, try this 

https://github.com/Jerem584/PacketTracerRecovery/releases/tag/8.2.1b

you can actually now inject no matter when

**Comment by jdut** [comment]
just tested on a fresh install
working 
thxs for your work
![image](https://github.com/Jerem584/PacketTracerRecovery/assets/11157901/4f4cf3b3-6122-409a-b5dd-f7e273d0e7f2)

**Comment by Lukas-Kadura** [comment]
Now it writes "Wait for a BEEP then press any key" but I don't hear any BEEP and it keeps asking me for the Packet Tracer password
![2](https://github.com/Jerem584/PacketTracerRecovery/assets/142180103/4d7b5f94-6a35-4423-86fb-f2fc3e17bac0)

**Comment by Jerem584** [comment]
open task manager, close every instance of packet tracer, relaunch it, and try again

**Comment by Jerem584** [comment]
make also sure to have c++ redistribuable and to have packet tracer 8.2.1 (x64)

**Comment by Lukas-Kadura** [comment]
Thanks, I'm fine now. I restarted the PC.
