### ISSUE TITLE
How to Use it?

### ISSUE THREAD

**Issue by zerotier000** [Jerem584/PacketTracerRecovery#2]
i still dont know how to use it can u make a tutorial video and upload on youtube?

**Comment by Jerem584** [comment]
Open packet tracer 8.2.1 and wait until it's fully loaded then run the exe that you will found under the release section

So

Step 1: run packet tracer
Step 2: execute the program here

**Comment by sharirh** [comment]
Hi, cant find the release section...or more instructions on how to do it myself...

**Comment by jdut33** [comment]
https://github.com/Jerem584/PacketTracerRecovery/releases/tag/8.2.1b for Jerem584 release
packer tracer is not provided here, you can download it on cisco webpage ( https://www.netacad.com/portal/resources/file/692e524f-12f9-46ef-9417-f03be70a2f77)

follow instructions given by Jerem584 on this page
